name: Auto pull from master

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Update branches
      run: |
        for branch in $(git branch --format='%(refname:short)'); do
          if [ "$branch" != "master" ]; then
            git checkout "$branch" && git pull origin master
          fi
        done
