name: Auto pull from master

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pull from master
      run: |
        git checkout master
        git pull origin master
